[tool.poetry]
name = "food-facilities-challenge"
version = "0.1.0"
package-mode = false
description = ""
authors = ["tmow12 <trevormow@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
uvicorn = "^0.34.3"
fastapi = "^0.115.12"
pandas = "^2.2.3"
pydantic = "^2.11.5"
geopy = "^2.4.1"
pytest-mock = "^3.14.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.0"
httpx = "^0.28.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
test = "pytest"